import "./app/boundary/MicroprofileStarterAppElement.ts"
import "./app/boundary/AppVersionElement.ts"
import "./form/boundary/MpStarterFormMpSpecs.ts"
import "./form/boundary/MpStarterFormJavaVersionAndBuildTool.ts"
import "./form/boundary/MpStarterFormProjectCoordinates.ts"
import "./form/boundary/MpStarterFormMpVersionsAndServer.ts"
import "./form/boundary/MpStarterForm.ts"
